server.ssl.enabled=true
server.ssl.certificate=file:D:/WXDEV/pw_backend/blackwinds.cn_bundle.pem
server.ssl.certificate-private-key=file:D:/WXDEV/pw_backend/blackwinds.cn.key
server.ssl.enabled-protocols=TLSv1.2,TLSv1.3
